name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: List output files
      run: ls -R app/build/outputs/apk

    - name: Setup rclone
      run: |
        mkdir -p ~/.config/rclone
        echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

    - name: Upload APK to Google Drive
      run: |
        APK_PATH=$(find app/build/outputs/apk/ -name "*.apk" | head -n 1)
        VERSION=$(echo "$APK_PATH" | grep -oP '\d+\.\d+\.\d+')
        DESTINATION="gdrive:MyApp/Versions/$VERSION/"
        
        echo "Uploading $APK_PATH to $DESTINATION"
        rclone copy "$APK_PATH" "$DESTINATION" --progress